### ISSUE TITLE
Audio is not sent when using LibreWolf

### ISSUE THREAD

**Issue by toboggan7** [IceDBorn/pipewire-screenaudio#11]
Audio isn't transmitted despite the menu being accessible after putting the native bridge in `~/.librewolf`. Known issue, putting this here to track any further developments.

**Comment by IceDBorn** [comment]
I'll try looking into it tomorrow. We're currently in the process of reworking the whole project and we don't have much time to test LibreWolf.

**Comment by IceDBorn** [comment]
I'll try looking into it tomorrow. We're currently in the process of reworking the whole project and we don't have much time to test LibreWolf.

**Comment by jim3692** [comment]
I have opened an issue on LibreWolf in order to understand what the problem is: https://gitlab.com/librewolf-community/browser/arch/-/issues/116

**Comment by IceDBorn** [comment]
It seems that this issue occurs when `privacy.resistFingerprinting` is enabled on Firefox-based browsers, there's info in the README on how to solve it.
