### ISSUE TITLE
Duplicated audio

### ISSUE THREAD

**Issue by Potajito** [IceDBorn/pipewire-screenaudio#16]
First of all, thanks for this! It's the best tool for discord streaming I've found so far. No fps drops, good video, audio... But when I stream with audio (first I select the audio, desktop or the app, tried both) but I hear the app twice, for some reason, and I can't seem to be able to silence that second one without silencing the original one. 
This is using discord on Firefox 115.0.2.
Any idea?

**Comment by IceDBorn** [comment]
Can you post a screenshot of `Helvum` taken while you're streaming audio?

**Comment by Potajito** [comment]
Hi, qpwgraph for the patches, hope that's ok, as it looks a bit more clear than helvum over here: 
![Screenshot_20230729_212126](https://github.com/IceDBorn/pipewire-screenaudio/assets/39760810/35ea5251-4e15-459d-9bb6-043834303073)

**Comment by IceDBorn** [comment]
Everything looks in order, no errors on Pipewire's side. I can't replicate this, nor any of the other devs, we'll need more information on this problem or at least a way to reproduce it.

**Comment by Potajito** [comment]
I've done some (lots) of testing, and I could only blame this on discord screen share:
- I was using a patched firefox vaapi, so when I realized that I tried plain firefox and developer/nightly, but there was no difference.
- Then I tried another webrtc apps, like this demo site (https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/#9378353810022836) or just jitsi, and that was working fine.
- So I guess basically the problem is the discord implementation? When I screen share on discord I get this weird bug where I get prompted twice for the screenshare (looking around, this seems like one permission for the small preview window and another for the actual stream, also you need to select both and can't skip either if you want the actual stream to work). This double prompt thing is probably related to some bugs like:

> https://bugzilla.redhat.com/show_bug.cgi?id=1891974
> https://bugzilla.mozilla.org/show_bug.cgi?id=1811341

**Comment by IceDBorn** [comment]
I almost passed out listening to this... How does Discord manage to ruin stuff all the time?

**Comment by Potajito** [comment]
> I almost passed out listening to this... How does Discord manage to ruin stuff all the time? Thanks a lot for testing this out btw. I'm currently on vacation, so it'll be a few more days before I can test it out too. Sorry for the inconvenience.

Hahaha, sorry for that, didn't want to trigger you. No worries, no rush, just drop me a message if you need any testing done.
Cheers!

**Comment by IceDBorn** [comment]
@Potajito Can you join the matrix space? I want you to try some more things.

**Comment by IceDBorn** [comment]
I'm using a hardened user.js made by arkenfox, on the other hand, I've overridden some settings for a better overall experience. Maybe one of the settings I've overridden fixes this issue?

**Comment by IceDBorn** [comment]
I managed to reproduce this on Hyprland, it's not a config issue.

**Comment by IceDBorn** [comment]
Fixed on latest release
