### ISSUE TITLE
Improve the installation section of the readme

### ISSUE THREAD

**Issue by Aviana** [IceDBorn/pipewire-screenaudio#23]
The installation section could be improved by explicitly stating that you have to install the add-on from the Mozilla store as well. Only having the link on the top right might be not enough.

**Comment by IceDBorn** [comment]
That's true, but I did not include it because I thought it was redundant. You can't use the native part without the extension (yet)

**Comment by dxcvvxd** [comment]
so this wont work on discord desktop apps like armcord???

**Comment by IceDBorn** [comment]
@dxcvvxd We're planning on making the native part independent from the extension. When this happens, anyone will be able to implement this into custom Discord clients like the one you mentioned. Actually, the native part can be used without the extension in its current state, but, we're planning a lot of backend/API changes, having modularity in mind.
