### ISSUE TITLE
connect-and-monitor.sh crashes because it fails to link (race condition)

### ISSUE THREAD

**Issue by alansartorio** [IceDBorn/pipewire-screenaudio#43]
While sharing, connect-and-monitor.sh process crashed. In the logs, I was able to see this:

```
[connect-and-monitor.sh] [Got New Node ID] ID: 271
[connect-and-monitor.sh] [Got Ports IDs] FL IDs: , FR IDs:
```

This is most probably a race condition, because we do:
[ask for node info](https://github.com/IceDBorn/pipewire-screenaudio/blob/26ccc7726440bd0f589f046b431212b86bbd87f4/native/connector/connect-and-monitor.sh#L68) -> [ask for a full `pw-dump` to get it's ports](https://github.com/IceDBorn/pipewire-screenaudio/blob/26ccc7726440bd0f589f046b431212b86bbd87f4/native/connector/connect-and-monitor.sh#L81) -> [connect them](https://github.com/IceDBorn/pipewire-screenaudio/blob/26ccc7726440bd0f589f046b431212b86bbd87f4/native/connector/connect-and-monitor.sh#L97).

The node can (and probably did) get removed between any of those steps, and it will crash when it reaches `pw-link`, which returns error exit status when it can't connect.
We either:
1. Prevent this race condition from occurring between the first and second step by unifying them and getting `pw-dump` since the beginning and then query that for getting node info and port ids. (kinda costly doing full pw-dump for every node)
2. Detect the race condition by checking if we successfully got the two ports in the second step (they shouldn't be empty strings).

But then if we lose the node before linking the ports, `pw-link` fails and because we've set `set -e`, the script will crash. So I think we should also ignore `pw-link` exit status code (`pw-link ... || true`) because we cant prevent this race condition.

**Comment by jim3692** [comment]
My suggestion is to implement a temporary solution (like checking for empty strings, or ignoring the exit status of `pw-link`) and have a fully working solution on 1.0.0 where we will not rely on `pw-dump`

**Comment by alansartorio** [comment]
I agree
