### ISSUE TITLE
micId variable from popup.js is sometimes set to "null" (string) instead of null

### ISSUE THREAD

**Issue by alansartorio** [IceDBorn/pipewire-screenaudio#51]
micId variable from `popup.js` is sometimes set to `"null"` (string) instead of `null`
The reason is that we don't parse it when we get it from localStorage.

This affects [a check](https://github.com/IceDBorn/pipewire-screenaudio/blob/a67a040f9a22854e52983c9305fe08fb10357260/extension/scripts/popup.js#L41) that is done in the `isRunning` function.

**Comment by IceDBorn** [comment]
https://github.com/IceDBorn/pipewire-screenaudio/commit/08ea01513da2b422511ac902aeb1c10a57019b0c
