### ISSUE TITLE
The addon does not work "The native connector is misconfigured or missing!"

### ISSUE THREAD

**Issue by DarkReaper231** [IceDBorn/pipewire-screenaudio#84]
I am on Arch Linux, I have installed both the pipewire-screenaudio from AUR repo and the addon, I disabled fingerprinting and I checked Allow on all websites.
The addon just shows "The native connector is misconfigured or missing!"

I use version 0.3.4-1 of the native part, not the git version
I use LibreWolf 119.0.1-1
I use pipewire-pulse (pipewire with pulseaudio)

**Comment by DarkReaper231** [comment]
Helvum doesn't show pipewire-screenaudio so the native part is not being loaded for whatever reason
![image](https://github.com/IceDBorn/pipewire-screenaudio/assets/38611351/c1f92279-5168-4321-9368-af224b0c774b)

**Comment by IceDBorn** [comment]
@DarkReaper231 The extension will not load the `pipewire-screenaudio` node until you press `Share`. @jim3692 is the maintainer of the AUR package, he'll help you.

**Comment by DarkReaper231** [comment]
> @DarkReaper231 The extension will not load the `pipewire-screenaudio` node until you press `Share`. @jim3692 is the maintainer of the AUR package, he'll help you.

No, even when I press share, it doesn't work

**Comment by IceDBorn** [comment]
You said that the extension is just showing "The native connector is misconfigured or missing!"

**Comment by DarkReaper231** [comment]
> You said that the extension is just showing "The native connector is misconfigured or missing!"

Yes and it doesn't work at all and helvum never shows the native part. It just doesn't work at all no matter if I screenshare or not. It always says "The native connector is misconfigured or missing!" even tho I have the native connector installed. I tried reinstalling it but no luck.

**Comment by IceDBorn** [comment]
I meant pressing the `Share` button on the extension.

**Comment by DarkReaper231** [comment]
> I meant pressing the `Share` button on the extension.

There's nothing share button, what do you mean

**Comment by DarkReaper231** [comment]
Okay it is using XDG, yeah so XDG in i3wm is funky just so you know

**Comment by IceDBorn** [comment]
The file `com.icedborn.pipewirescreenaudioconnector.json` should be located in `~/.mozilla/native-messaging-hosts` if you cloned the project and installed the native part with `install.sh` or `/usr/lib/mozilla/native-messaging-hosts/com.icedborn.pipewirescreenaudioconnector.json` if you installed the native part using the AUR package.

The `Share` button is missing because there's something wrong with the communication between the extension and the native part. I would suggest you to try uninstalling the package, installing the dependencies yourself and then cloning the project and running `install.sh`.

**Comment by jim3692** [comment]
Hello, sorry for the late reply. I was not available during the past days.

Regarding the XDG point, we are only using the `XDG_RUNTIME_DIR` variable, whose value is usually `/run/user/1000`.

**Comment by IceDBorn** [comment]
https://librewolf.net/docs/faq/#how-do-i-get-native-messaging-to-work

**Comment by DarkReaper231** [comment]
After manually making the folder and copying the json file over, it now works
![image](https://github.com/IceDBorn/pipewire-screenaudio/assets/38611351/62271d8c-9787-4844-a7f5-821cd623e44b)

**Comment by jim3692** [comment]
Instead of trying to have all browsers in a single AUR package, I published a new one specifically for LibreWolf:
https://aur.archlinux.org/packages/pipewire-screenaudio-librewolf

**Comment by DarkReaper231** [comment]
@IceDBorn I am testing it by calling myself on phone and on the phone I hear no audio, despite sharing is enabled, I screenshare as well. There is no audio coming through
![image](https://github.com/IceDBorn/pipewire-screenaudio/assets/38611351/718b1736-b555-472c-ac86-10ecfed5b1b0)

**Comment by jim3692** [comment]
Did you get a popup for permission to use the `pipewire-screenaudio` mic after starting the screensharing?

![image](https://github.com/IceDBorn/pipewire-screenaudio/assets/31220180/770720bf-1a92-4658-9ce2-44d314c89d07)

**Comment by DarkReaper231** [comment]
@jim3692 No I didn't

**Comment by DarkReaper231** [comment]
![image](https://github.com/IceDBorn/pipewire-screenaudio/assets/38611351/790ffd9a-ddc6-46a2-bb62-98b70204adcc)
Oh I can only allow one microphone at once. I restarted LibreWolf and selected pipewire-screenaudio and now it works.

**Comment by DarkReaper231** [comment]
But it pipes audio into microphone, it sounds like shit with all the postprocessing Discord throws at the output. Is there a way to fix that?

**Comment by jim3692** [comment]
> ![image](https://private-user-images.githubusercontent.com/38611351/289483776-790ffd9a-ddc6-46a2-bb62-98b70204adcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODYzMTksIm5iZiI6MTcwMjI4NjAxOSwicGF0aCI6Ii8zODYxMTM1MS8yODk0ODM3NzYtNzkwZmZkOWEtZGRjNi00NmEyLWJiNjItOThiNzAyMDRhZGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA5MTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMGE3Mzc5ZGMyY2JhY2EyMmMxODBmY2EzMjY3ZDRhYzRmNGQyZTA4ZjcyMGQ2MmYyYjI4ZWNhNjQ4MGNhYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6xmYO-d0Zj2-T9nkaJixjpXscs5DxR4MHm2jopdTNzk) Oh I can only allow one microphone at once. I restarted LibreWolf and selected pipewire-screenaudio and now it works.

You should not select `pipewire-screenaudio` from that dialog. That is your actual microphone.

**Comment by DarkReaper231** [comment]
> > ![image](https://private-user-images.githubusercontent.com/38611351/289483776-790ffd9a-ddc6-46a2-bb62-98b70204adcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODYzMTksIm5iZiI6MTcwMjI4NjAxOSwicGF0aCI6Ii8zODYxMTM1MS8yODk0ODM3NzYtNzkwZmZkOWEtZGRjNi00NmEyLWJiNjItOThiNzAyMDRhZGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA5MTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMGE3Mzc5ZGMyY2JhY2EyMmMxODBmY2EzMjY3ZDRhYzRmNGQyZTA4ZjcyMGQ2MmYyYjI4ZWNhNjQ4MGNhYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6xmYO-d0Zj2-T9nkaJixjpXscs5DxR4MHm2jopdTNzk) Oh I can only allow one microphone at once. I restarted LibreWolf and selected pipewire-screenaudio and now it works.
> 
> You should not select `pipewire-screenaudio` from that dialog. That is your actual microphone.

Oh, well in that case there's no other popup

**Comment by jim3692** [comment]
I got a fresh LibreWolf, I set `privacy.resistFingerprinting` to false in `about:config` and installed the extension. That seems to work. I am get the popup and the pipes correctly connect.

**Comment by DarkReaper231** [comment]
@jim3692 When I disable resistFingerprinting, it also starts working for me but it's really funky. In order to make it work, I have to do these steps:
1. Join discord call and allow my microphone
2. Press Share in the addon (here's where the funkyness begins)
3. I **HAVE** to press Switch Device here otherwise it won't work
![image](https://github.com/IceDBorn/pipewire-screenaudio/assets/38611351/12e98316-24e3-4387-aee6-0660550864ed)
4. I have to press Allow here
![image](https://github.com/IceDBorn/pipewire-screenaudio/assets/38611351/e6e47056-edcb-49da-8748-4dede0ef29ba)
5. Now I have to select my mic back, because it's getting piped into my mic
![image](https://github.com/IceDBorn/pipewire-screenaudio/assets/38611351/ed7ea919-71fd-4020-81d5-b9a6d2bb3232)
6. I start the screenshare in Discord
7. Now I have to press "Share" in the addon again because it got disabled in the meanwhile
8. Now it works correctly

Problem is that step 7 doesn't always work. If it doesn't work, it will just always show the "Switch Device" dialogue and I never get it working properly

**Comment by DarkReaper231** [comment]
Oh and 70% of times the audio is changing speed or some shit, it's super weird and it makes the audio funky as hell

**Comment by DarkReaper231** [comment]
@jim3692 Why is it like this?

https://github.com/IceDBorn/pipewire-screenaudio/assets/38611351/c52c6134-4c24-4d94-bf0d-1c9c51124499

**Comment by DarkReaper231** [comment]
Installing latest Librewolf fixed it but the audio is still not anywhere near the quality that it is on WIndows. Also it cuts out every 3 seconds or so.
