### ISSUE TITLE
Not able to get it working on Firefox Nightly + Discord

### ISSUE THREAD

**Issue by Sid127** [IceDBorn/pipewire-screenaudio#9]
As the title says, I have the AUR package installed, as well as the extension, and any/all discord streams still have no audio. I'm running sway, if the environment/display server makes a difference.

**Comment by IceDBorn** [comment]
1. Open the browser console, reload the page and check if you can find `pipewire-screenaudio script injected`
2. Open helvum and check if the node `pipewire-screenaudio` is present and connected to Firefox and the node you want to share
3. I'm not sure if it works with other browsers than the stable version, I tried using it with LibreWolf for example and it did not work

**Comment by Sid127** [comment]
Quick question. Is it meant to work like the discord-screenaudio userscripts, where the audio goes through the WebRTC node itself, or does it work like the old workaround of having to route the audio you want to stream via your microphone?

**Comment by IceDBorn** [comment]
> Quick question. Is it meant to work like the discord-screenaudio userscripts, where the audio goes through the WebRTC node itself, or does it work like the old workaround of having to route the audio you want to stream via your microphone?

No, it does not use your microphone, it connects directly to the node created from WebRTC

**Comment by IceDBorn** [comment]
> any/all discord streams still have no audio

Have you tried streaming to another platform?

**Comment by IceDBorn** [comment]
Also, we are currently reworking the whole project, we're going to ditch the C++ binary and migrate to pure bash. All Desktop Audio will be the default and it'll be enabled by default, without user interaction, unless you specify a specific node or nodes. If your problem has something to do with the native part not functioning correctly, I suggest that you wait until the migration is done.

**Comment by Sid127** [comment]
ok, apparently restarting firefox after installing the native bit wasn't enough, a full system reboot later the audio works. However shared audio has audio quality/pitching issues as also existed on the discord-screenaudio userscripts, so I guess that's just something I'll have to deal with or find a way to work around. Thank you for your time!

**Comment by IceDBorn** [comment]
@Sid127 I don't have any problems with the audio quality, I think that's a problem with your configuration and Firefox, not something we can do to fix it unfortunately 😢
