### ISSUE TITLE
The native connector is misconfigured or missing! for linux mint 

### ISSUE THREAD

**Issue by Schweiger-Jacob** [IceDBorn/pipewire-screenaudio#90]
I ran the install script and downloaded the extension and this is all the extension shows.

**Comment by alansartorio** [comment]
Are you using the snap/flatpack version of Firefox?

**Comment by IceDBorn** [comment]
Do you have all the dependencies installed?

**Comment by IceDBorn** [comment]
https://github.com/IceDBorn/pipewire-screenaudio/issues/96
