### ISSUE TITLE
What is the "correct" way to re-add voice input?

### ISSUE THREAD

**Issue by Jackiecrazy** [IceDBorn/pipewire-screenaudio#92]
I am using this extension to stream on discord calls on Manjaro Firefox. Everything works as advertised, but when I point the Discord microphone to pipewire-screenaudio, regardless of which audio source I choose (including [all desktop audio]), my voice no longer gets picked up. I can use Helvum to re-attach the microphone to the WebRTC engine, but that also means I cannot individually modify the volume of my talking and the audio being streamed, and those in the chat are telling me that my voice is very soft. What is the correct way to re-add voice to mitigate this issue? Helvum setup has been attached, linked to a video I have open on Firefox and the microphone, and feeding back to Discord's mic testing.
![image](https://github.com/IceDBorn/pipewire-screenaudio/assets/6895485/b744bc80-d9dd-4ad3-95bf-7d7c6a051ab4)

**Comment by alansartorio** [comment]
You shouldn't need to point the discord microphone to pipewire-screenaudio, the "pipewire-screenaudio" node should connect automatically to Firefox when you start sharing your screen.

**Comment by Jackiecrazy** [comment]
Yep, that works. Thank you!

**Comment by IceDBorn** [comment]
> As an aside, is there a way to individually change the output volume so the shared screen's sounds are softened when sent to my headphones, but played at normal volume for viewers on Discord? The sounds get a bit loud and I can't hear other people in the call very well.

https://github.com/IceDBorn/pipewire-screenaudio/issues/91
